"""Macro Intelligence — Pydantic schemas and data models.

All macro data flows through these typed models.
GCC-specific indicators, regime types, and sector mappings.
"""

from __future__ import annotations

import hashlib
import json
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class RegimeType(str, Enum):
    """Macroeconomic regime classification — GCC-tuned."""
    EXPANSION = "expansion"
    TIGHTENING = "tightening"
    INFLATIONARY = "inflationary"
    RECESSION = "recession"
    OIL_BOOM = "oil_boom"
    OIL_SHOCK = "oil_shock"
    NEUTRAL = "neutral"


class SignalDirection(str, Enum):
    """Signal movement direction."""
    UP = "up"
    DOWN = "down"
    NEUTRAL = "neutral"


# ---------------------------------------------------------------------------
# Core models
# ---------------------------------------------------------------------------

class MacroIndicator(BaseModel):
    """A single macroeconomic indicator reading."""
    name: str = Field(..., description="Indicator name (e.g. 'brent_crude')")
    value: float = Field(..., description="Current value")
    previous: float | None = Field(default=None, description="Previous period value")
    unit: str = Field(default="", description="Unit (%, USD, index)")
    source: str = Field(default="manual", description="Data source")

    @property
    def change(self) -> float | None:
        """Absolute change from previous."""
        if self.previous is not None:
            return self.value - self.previous
        return None

    @property
    def pct_change(self) -> float | None:
        """Percentage change from previous."""
        if self.previous is not None and self.previous != 0:
            return (self.value - self.previous) / abs(self.previous)
        return None


class MacroSignal(BaseModel):
    """A derived macro signal — generated by the Signal Engine."""
    name: str = Field(..., description="Signal identifier")
    strength: float = Field(..., ge=0.0, le=1.0, description="Signal strength 0–1")
    direction: SignalDirection = Field(..., description="Signal direction")
    source_indicators: list[str] = Field(
        default_factory=list,
        description="Which indicators triggered this signal",
    )
    description: str = Field(default="", description="Human-readable description")
    description_ar: str = Field(default="", description="Arabic description")


class SectorImpact(BaseModel):
    """Macro-driven impact on a specific sector."""
    sector: str = Field(..., description="Target sector")
    impact_score: float = Field(
        ..., ge=-1.0, le=1.0,
        description="Impact magnitude (-1 = severe negative, +1 = strong positive)",
    )
    direction: SignalDirection = Field(..., description="Impact direction")
    contributing_signals: list[str] = Field(
        default_factory=list,
        description="Signals that contribute to this impact",
    )
    reasoning: str = Field(default="", description="Why this impact exists")


class MacroContext(BaseModel):
    """Complete macro intelligence context — output of the Orchestrator."""
    regime: RegimeType = Field(..., description="Current macro regime")
    regime_confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence in regime classification",
    )
    signals: list[MacroSignal] = Field(
        default_factory=list, description="Active macro signals",
    )
    sector_impacts: list[SectorImpact] = Field(
        default_factory=list, description="Sector-level impact assessments",
    )
    indicators_snapshot: dict[str, float] = Field(
        default_factory=dict, description="Raw indicator values used",
    )
    risk_overlay: float = Field(
        default=0.0,
        description="Aggregate macro risk adjustment (-0.3 to +0.3)",
    )
    audit_hash: str = Field(default="", description="SHA-256 audit hash")

    def to_dict(self) -> dict[str, Any]:
        return {
            "regime": self.regime.value,
            "regime_confidence": round(self.regime_confidence, 4),
            "signals": [s.model_dump() for s in self.signals],
            "sector_impacts": [s.model_dump() for s in self.sector_impacts],
            "indicators_snapshot": {
                k: round(v, 6) for k, v in self.indicators_snapshot.items()
            },
            "risk_overlay": round(self.risk_overlay, 6),
            "audit_hash": self.audit_hash,
        }


class MacroPortfolioOverlay(BaseModel):
    """Macro overlay applied to portfolio risk analysis."""
    portfolio_entities: list[str]
    base_portfolio_risk: float
    macro_adjusted_risk: float
    macro_adjustment: float
    regime: RegimeType
    sector_adjustments: list[dict[str, Any]]
    reasoning: list[str]
    audit_hash: str


class MacroUnderwritingOverlay(BaseModel):
    """Macro overlay applied to underwriting decisions."""
    entity_id: str
    base_risk_score: float
    macro_adjusted_score: float
    macro_adjustment: float
    regime: RegimeType
    pricing_impact: str
    sector_impact: SectorImpact | None
    conditions_added: list[str]
    reasoning: list[str]
    audit_hash: str


# ---------------------------------------------------------------------------
# API request model
# ---------------------------------------------------------------------------

class IndicatorsInput(BaseModel):
    """API request body for macro analysis."""
    brent_crude: float | None = Field(
        default=None,
        description="Brent crude oil price (USD/barrel)",
        json_schema_extra={"example": 82.5},
    )
    interest_rate: float | None = Field(
        default=None,
        description="Central bank policy rate (decimal, e.g. 0.055 = 5.5%)",
        json_schema_extra={"example": 0.055},
    )
    inflation: float | None = Field(
        default=None,
        description="CPI inflation rate (decimal, e.g. 0.035 = 3.5%)",
        json_schema_extra={"example": 0.035},
    )
    gdp_growth: float | None = Field(
        default=None,
        description="GDP growth rate (decimal, e.g. 0.03 = 3%)",
        json_schema_extra={"example": 0.03},
    )
    fx_usd_sar: float | None = Field(
        default=None,
        description="USD/SAR exchange rate",
        json_schema_extra={"example": 3.75},
    )
    credit_growth: float | None = Field(
        default=None,
        description="Credit growth rate (decimal)",
        json_schema_extra={"example": 0.08},
    )
    pmi: float | None = Field(
        default=None,
        description="Purchasing Managers Index",
        json_schema_extra={"example": 54.2},
    )
    real_estate_index: float | None = Field(
        default=None,
        description="Real estate price index (100 = baseline)",
        json_schema_extra={"example": 105.0},
    )
    trade_balance: float | None = Field(
        default=None,
        description="Trade balance (billion USD)",
        json_schema_extra={"example": 15.2},
    )
    govt_spending_growth: float | None = Field(
        default=None,
        description="Government spending growth rate (decimal)",
        json_schema_extra={"example": 0.05},
    )
    vix: float | None = Field(
        default=None,
        description="VIX volatility index",
        json_schema_extra={"example": 18.5},
    )
    shipping_cost_index: float | None = Field(
        default=None,
        description="Shipping cost index (100 = baseline)",
        json_schema_extra={"example": 110.0},
    )

    def to_indicator_dict(self) -> dict[str, float]:
        """Convert to flat dict, excluding None values."""
        return {
            k: v
            for k, v in self.model_dump().items()
            if v is not None
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def compute_macro_audit_hash(
    regime: str,
    signals_count: int,
    risk_overlay: float,
    indicators: dict[str, float],
) -> str:
    """SHA-256 audit hash for macro context."""
    payload = json.dumps({
        "regime": regime,
        "signals_count": signals_count,
        "risk_overlay": round(risk_overlay, 6),
        "indicator_keys": sorted(indicators.keys()),
    }, sort_keys=True)
    return hashlib.sha256(payload.encode()).hexdigest()
